# Generated by Django 5.0.6 on 2024-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=100)),
                ('noteMedical', models.TextField(max_length=500)),
                ('UltrasoundImg', models.ImageField(upload_to='UltrasoundImgs/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
